### ISSUE TITLE
Minor Error list

### ISSUE THREAD

**Issue by casionone** [apache/linkis-website#390]
Used to record errors on the official website

- typo
- link error
- information display error
- display content errors
- etcd.

-----------
用于记录官网细小错误点 如
- 错字/拼写错误
- 链接错误
- 信息显示错误
- 显示内容错误
- .....等等

**Comment by casionone** [comment]
![image](https://user-images.githubusercontent.com/7869972/176670033-f411b255-b434-4b63-a9bc-828b1a1cf731.png)

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/179133836-b5a4a9ed-9879-45d4-8981-d5c883b4af47.png)
SSSS

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/179138678-af0f4b8c-9c7e-4889-953f-0ca922328db1.png)
文档风格不统一

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/179139348-fe6a531c-9e1c-4427-8fb7-05d7b0695324.png)
文档网络不统一

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/179141714-b9068753-69bb-4c7c-8e17-58fc8c08804d.png)

二维码太大

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/179141951-36866df5-a6c7-4410-b50b-08b411592326.png)

![image](https://user-images.githubusercontent.com/22620332/179141998-226f867d-325f-4c07-abd3-176db195107e.png)


标点符号使用错误

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/179142562-8a06d9ad-283a-47ba-b3a1-bc7c0b3d8ae2.png)


修改建议

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/179145199-3875d0ef-58d9-461d-86bb-092444a563ee.png)

![image](https://user-images.githubusercontent.com/22620332/179145296-c8c4c4f2-6e6c-461a-8fcc-cbe4003944d8.png)


书写不规范

**Comment by casionone** [comment]
![image](https://user-images.githubusercontent.com/7869972/179239360-3ef4fec8-0ab3-495b-9cf5-0b27487f8f42.png)

**Comment by aiceflower** [comment]
![image](https://user-images.githubusercontent.com/22620332/182064408-4b65ff94-4830-41a0-85d7-4aa6f10b9a9e.png)

----
![image](https://user-images.githubusercontent.com/22620332/182551983-b155f5cc-dcae-4486-8a09-c02b04e878b0.png)


错别字

**Comment by casionone** [comment]
![image](https://user-images.githubusercontent.com/7869972/202185832-c66f5d2c-bec8-4ae5-9dbf-4c4e623417b1.png)

**Comment by binbinCheng** [comment]
**serial number format error（序列号格式错误）**

![image](https://user-images.githubusercontent.com/106590848/205004293-15231eea-55b0-4f08-848a-25a145304f40.png)

**Comment by binbinCheng** [comment]
**English documentation exists in Chinese（英文文档有中文）**

![image](https://user-images.githubusercontent.com/106590848/205004744-74f11242-c890-4ee8-8d4d-3ea7963c2f9d.png)

**Comment by casionone** [comment]
![image](https://user-images.githubusercontent.com/7869972/205640224-aee9e9eb-b9ad-47d5-a2f9-72fc0ba8b40a.png)

**Comment by casionone** [comment]
![企业微信截图_16720378061285](https://user-images.githubusercontent.com/7869972/209515616-76d45bd6-8df4-40a5-9c24-d4c5a1b2bbea.png)
----

![企业微信截图_16720378582101](https://user-images.githubusercontent.com/7869972/209516601-32b476bc-312c-4d29-8181-6db7b68d8b0c.png)
-----

![企业微信截图_16720379658553](https://user-images.githubusercontent.com/7869972/209515635-d62a2358-99f6-43a9-97af-37d2e090c32c.png)

-----

![企业微信截图_16720380082969](https://user-images.githubusercontent.com/7869972/209515653-a581fcf2-d64e-435b-9da9-42d0de912bda.png)

**Comment by casionxia** [comment]
get
